### ISSUE TITLE
warnings emitted by msvc

### ISSUE THREAD

**Issue by Tisten** [jeaiii/itoa#11]
When compiling with MSVC I'm getting warnings:
jeaiii_to_text.h(147): warning C4305: '/=': truncation from 'jeaiii::u32' to 'U'
jeaiii_to_text.h(209): warning C4305: '/=': truncation from 'jeaiii::u32' to 'U'

Replacing
```
n /= u32(1e8);
```
by
```
n = U(n /u32(1e8));
```
solves it.

**Comment by jeaiii** [comment]
does `n /= U(1e8);` fix it too?

**Comment by Tisten** [comment]
Well, 1e8 doesn't fit in uint8_t so you will get non-working code and these instead:
warning C4310: cast truncates constant value
warning C4723: potential divide by 0

**Comment by jeaiii** [comment]
ah, because the MSVC compiler didn't realize that n can't be a uint8_t at that point in the code...okay

**Comment by jeaiii** [comment]
clean to warning level 4
https://github.com/jeaiii/itoa/commit/ebde9d35255b3bf5c2af67293990bade67439382
