### ISSUE TITLE
Issue in integer to string conversion

### ISSUE THREAD

**Issue by praveensingh0828** [jeaiii/itoa#12]
This failed to convert this number: 3890001770327310336.

This resulted in 3890001770227310336 (Diff of 10'000'000)

**Comment by jeaiii** [comment]
which version?

**Comment by jeaiii** [comment]
fixed in https://github.com/jeaiii/itoa/commit/1c92f1f4f4b5c82857a8077071a3d13efe51743d and tested all 100,000,000 8 digits sub blocks https://godbolt.org/z/hTEWPKTPG

**Comment by jeaiii** [comment]
only newest non macro version had this issue
