### ISSUE TITLE
Versions for uint8_t, int8_t, uint16_t and int16_t

### ISSUE THREAD

**Issue by luizpara** [jeaiii/itoa#16]
This is a fantastic, really fast algorithm, that even seems to beat Vitaut's. Many thanks for making this available.

My issue is actually a feature request. For completion, do you think that beyond the currently available implementations for `uint32_t`, `int32_t`, `uint64_t` and `int64_t`, would it be possible to add, in the future, implementations also for `uint8_t`, `int8_t`, `uint16_t` and `int16_t`?

It would be amazing to have those, for really fast conversion of low-latency batches of data.

**Comment by jeaiii** [comment]
the current version handles all integer types and produces well optimized specialized code based on the size, signed/unsigned, and other range limits the compiler can detect
