### ISSUE TITLE
GCC warning due to ASCII art

### ISSUE THREAD

**Issue by davidgaleano** [jeaiii/itoa#6]
The ASCII art on "to_text_from_integer.h" generates a compiler warning with GCC 8:
```
itoa/to_text_from_integer.h:39:1: warning: multi-line comment [-Wcomment]
 //    /\   \     \     \     \
 ^
```
If you comment that line on the header file you also get a warning on the next one. I think it is due to the use of the character "\\".

**Comment by jeaiii** [comment]
thanks, will fix in next version which makes it even faster

**Comment by davidgaleano** [comment]
Thanks. It would be an awesome version then

**Comment by jeaiii** [comment]
try new version jeaiii_to_text.h also about 25% faster for random uniform digit lengths

**Comment by davidgaleano** [comment]
Sorry but it fails to compile with GCC:
```
itoa/itoa/jeaiii_to_text.h:72:23: error: ‘__forceinline’ does not name a type
     template<class T> __forceinline
                       ^~~~~~~~~~~~~
```

**Comment by davidgaleano** [comment]
And if I remove "__forceinline" then I get lots of warnings like this one:
```
itoa/itoa/jeaiii_to_text.h:92:45: warning: suggest parentheses around ‘-’ in operand of ‘&’ [-Wparentheses]
                 auto f2 = (f0 & u32(0x1p24) - 1) * 100;
                                 ~~~~~~~~~~~~^~~
```
(which could be a bit pedantic but I thought I should let you know just in case)

**Comment by jeaiii** [comment]
I think I've tried -Wall on godbolt on every c++ compiler now...

**Comment by davidgaleano** [comment]
It functions perfectly well now, thanks a lot for you work.
